return {
	"nvim-treesitter/nvim-treesitter",
	branch = "master",
	build = ":TSUpdate",
	cmd = { "TSUpdate", "TSInstall", "TSLog", "TSUninstall" },
	event = { "BufReadPre", "BufNewFile" },
	dependencies = {
		"windwp/nvim-ts-autotag",
	},
	config = function()
		require("nvim-treesitter.configs").setup({
			ensure_installed = {
				"lua",
				"vim",
				"vimdoc",
				"cpp",
				-- "latex",
				"python",
				"bash",
				"typescript",
				"javascript",
				"html",
				"css",
				"scss",
				"markdown",
				"markdown_inline",
				"yaml",
				"json",
				"ruby",
				"tsx",
				"cmake",
				"awk",
				"gitignore",
				"dockerfile",
				"toml",
				"luadoc",
				"luap",
			},
			modules = {},
			sync_install = false,
			ignore_install = {},
			auto_install = true,
			highlight = { enable = true },
			indent = { enable = true },
			autotag = { enable = true },
			fold = { enable = true },
			incremental_selection = {
				enable = true,
				keymaps = {
					init_selection = "<C-space>",
					node_incremental = "<C-space>",
					scope_incremental = false,
					node_decremental = "<bs>",
				},
			},
		})
	end,
}
