set -g status-style "bg=terminal" # remove default background color

# status left look and feel
set -g status-left-length 100
set -g status-left ""
set -ga status-left "#{?client_prefix,#{#[fg=#{@thm_bg},bg=#{@thm_red},bold]  #S },#{#[fg=#{@session_color},none]  #S }}" # session name & icon, whitespace as padding
set -ga status-left "#[fg=#{@thm_fg},bg=terminal,none]│" # separator
set -ga status-left "#[fg=#{@pane_color}]  #{pane_current_command} " # pane and icon
set -ga status-left "#[fg=#{@thm_fg},bg=terminal,none]│" # separator
set -ga status-left "#[fg=#{@path_color}]  #{=/-32/...:#{s|$USER|~|:#{b:pane_current_path}}} " # pane path
set -ga status-left "#{?window_zoomed_flag,#[fg=#{@maximize_color},bold]  MAX #[none],}" # pane is maximized?

# CENTER
set -g status-justify "absolute-centre"
set -g window-status-format " #I#{?#{!=:#{window_name},Window},: #W,} "
set -g window-status-style "fg=#{@window_color}"
# set -g window-status-last-style "fg=#{@active_window_color}"
set -g window-status-last-style "bold"
set -g window-status-activity-style "bg=#{@thm_red},fg=#{@thm_bg}"
set -g window-status-bell-style "bg=#{@thm_red},fg=#{@thm_bg},bold"
set -gF window-status-separator "#[fg=#{@thm_white_b}]│"

set -g window-status-current-format " #I#{?#{!=:#{window_name},Window},: #W,} "
set -g window-status-current-style "bg=#{@active_window_color},fg=#{@thm_bg},bold"

# status right look and feel
set -g status-right-length 150
set -g status-right ""
# set -ga status-right "" # weather
# set -ga status-right "#[fg=#{@thm_fg},bg=terminal,none]│" # separator
# set -ga status-right " #{@pomodoro_status}  bla" # pomodoro
# set -ga status-right "#[fg=#{@thm_fg},bg=terminal,none]│" # separator
# set -ga status-right " 󰔛 #{project_time} " # uptime
# set -ga status-right "#[fg=#{@thm_fg},bg=terminal,none]│" # separator
set -ga status-right "#{?#{e|>=:15,#{battery_percentage}},#{#[bg=#{@battery_low_color},fg=#{@thm_bg}]},#{#[bg=terminal,fg=#{@battery_color}]}} #{battery_icon} #{battery_percentage} "
set -ga status-right "#[fg=#{@thm_fg},bg=terminal,none]│" # separator
set -ga status-right "#[fg=#{@date_color}] 󰭦 %d.%m.%Y %a #[fg=#{@time_color}]󰅐 %H:%M " # datetime
