
set -g status-style "bg=#{@thm_bg},fg=#{@thm_faint}"

# TODO: make it taller
# change font

# status left look and feel
set -g status-left-length 100
set -g status-left ""
set -ga status-left "#{?client_prefix,#{#[fg=#{@thm_bg},bg=#{@thm_secondary},bold] WAIT },#{#[fg=#{@thm_bg},bg=#{@thm_accent},none] TMUX }}" # session name & icon, whitespace as padding
set -ga status-left "#{?client_prefix,#{#[bg=#{@thm_bg},fg=#{@thm_secondary}]},#{#[bg=#{@thm_bg},fg=#{@thm_accent},none]}}" # session name & icon, whitespace as padding
set -ga status-left "#{#[bg=#{@thm_bg},fg=#{@thm_faint},none] 󰭦 %d.%m.%Y %a 󰅐 %H:%M }" # datetime

# CENTER
set -g status-justify "absolute-centre"
set -g window-status-format " #I: #{?#{!=:#{window_name},Window},#W,#{pane_current_command}} "
set -g window-status-current-format " #[fg=#{@thm_accent},bold]#I: #[fg=#{@thm_fg}]#{?#{!=:#{window_name},Window},#W,#{pane_current_command}}"

# status right look and feel
set -g status-right-length 150
set -g status-right ""
set -ga status-right "#{#[bg=#{@thm_bg},fg=#{@thm_faint},none] #{battery_icon} #{battery_percentage} }"
