# ALACRITTY NORDIC THEME COlORS

set -g @thm_bg "#242933"
set -g @thm_fg "#bbbdaf"

set -g @thm_black "#191c1d"
set -g @thm_red "#bd6062"
set -g @thm_green "#a3d6a9"
set -g @thm_yellow "#f0dfaf"
set -g @thm_blue "#8fb4d8"
set -g @thm_magenta "#c7a9d9"
set -g @thm_cyan "#b6d7a8"
set -g @thm_white "#bdc5bd"

set -g @thm_black_b "#727c7c"
set -g @thm_red_b "#d18faf"
set -g @thm_green_b "#b7ceb0"
set -g @thm_yellow_b "#bcbcbc"
set -g @thm_blue_b "#e0cf9f"
set -g @thm_magenta_b "#c7a9d9"
set -g @thm_cyan_b "#bbda97"
set -g @thm_white_b "#bdc6bd"

# SECTION COLORS
set -gF @session_color "#{@thm_green}"
set -gF @pane_color "#{@thm_red_b}"
set -gF @path_color "#{@thm_blue}"
set -gF @maximize_color "#{@thm_yellow}"

set -gF @window_color "#{@thm_white_b}"
set -gF @active_window_color "#{@thm_blue_b}"

set -gF @battery_low_color "#{@thm_red}"
set -gF @battery_color "#{@thm_magenta_b}"
set -gF @pomodoro_color "#{@thm_cyan}"
set -gF @weather_color "#{@thm_fg}"
set -gF @uptime_color "#{@thm_white_b}"
set -gF @date_color "#{@thm_fg}"
set -gF @time_color "#{@thm_white}"

# MISC
set -gF @thm_accent "#{@thm_magenta}"
set -gF @thm_secondary "#{@thm_green}"
set -gF @thm_faint "#{@thm_black_b}"
