set -g @thm_bg "#1a1b26"
set -g @thm_fg "#a9b1d6"

set -g @thm_black "#32344a"
set -g @thm_red "#f7768e"
set -g @thm_green "#9ece6a"
set -g @thm_yellow "#e0af68"
set -g @thm_blue "#7aa2f7"
set -g @thm_magenta "#ad8ee6"
set -g @thm_cyan "#449dab"
set -g @thm_white "#787c99"

set -g @thm_black_b "#444b6a"
set -g @thm_red_b "#ff7a93"
set -g @thm_green_b "#b9f27c"
set -g @thm_yellow_b "#ff9e64"
set -g @thm_blue_b "#7da6ff"
set -g @thm_magenta_b "#bb9af7"
set -g @thm_cyan_b "#0db9d7"
set -g @thm_white_b "#acb0d0"

# SECTION COLORS
set -gF @session_color "#{@thm_green}"
set -gF @pane_color "#{@thm_red_b}"
set -gF @path_color "#{@thm_blue}"
set -gF @maximize_color "#{@thm_yellow}"

set -gF @window_color "#{@thm_white_b}"
set -gF @active_window_color "#{@thm_yellow_b}"

set -gF @battery_low_color "#{@thm_red}"
set -gF @battery_color "#{@thm_magenta}"
set -gF @pomodoro_color "#{@thm_cyan}"
set -gF @weather_color "#{@thm_fg}"
set -gF @uptime_color "#{@thm_white}"
set -gF @date_color "#{@thm_fg}"
set -gF @time_color "#{@thm_white}"

# MISC
set -gF @thm_accent "#{@thm_magenta}"
set -gF @thm_secondary "#{@thm_green}"
set -gF @thm_faint "#{@thm_black_b}"
